[package]
name = "texture-unpacker"
version = "0.1.0"
authors = ["Vigdail"]
edition = "2018"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json="1.0.40"
image="0.22"
getopts="0.2.21"